name: Deploy Next.js Container

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/pibbie-web:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy on Self-Hosted VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/pibbie-web:latest
            docker pull $IMAGE_NAME
            docker stop pibbie-web || true
            docker rm pibbie-web || true
            docker run -d --name pibbie-web -p 5000:3000 $IMAGE_NAME