name: Deploy Next.js Container

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ secrets.IMAGE_REPOSITORY }}:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy on Self-Hosted
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ secrets.IMAGE_REPOSITORY }}:latest

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

            docker pull $IMAGE_NAME || exit 1

            if [ "$(docker ps -aq -f name=${{ secrets.DEV_CONTAINER_NAME }})" ]; then
              docker stop ${{ secrets.DEV_CONTAINER_NAME }}
              docker rm ${{ secrets.DEV_CONTAINER_NAME }}
            fi

            docker run -d --name ${{ secrets.DEV_CONTAINER_NAME }} -p ${{ secrets.DEV_PORT }}:3000 $IMAGE_NAME